In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('noida_flats1.csv')
df.head()

,Unnamed: 0,Area in Sqrt,No.of Bhk,Location,Price
0,0,3720,4,"Sector 107, Noida",3.9 Cr
1,1,1625,3,"Sector 50, Noida",1.15 Cr
2,2,1325,3,"Sector 120, Noida",60 L
3,3,650,1,"Sector 73, Noida",19 L
4,4,950,2,"Phase 2 Noida Extension, Noida",25.99 L

In [3]:
df.shape

(4460, 5)

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4460 entries, 0 to 4459
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Unnamed: 0    4460 non-null   int64
 1   Area in Sqrt  4460 non-null   int64
 2   No.of Bhk     4460 non-null   int64
 3   Location      4460 non-null   str
 4   Price         4460 non-null   str
dtypes: int64(3), str(2)
memory usage: 278.7 KB

In [10]:
for column in df.columns:
    print(df[column].value_counts())
    print ("*"*20)

Area in Sqrt
950     211
1050    146
1100     70
1750     56
650      54
       ...
3625      1
1174      1
5530      1
2210      1
440       1
Name: count, Length: 628, dtype: int64
********************
No.of Bhk
3     1774
2     1343
4      875
1      262
5      142
6       20
8       14
7       13
10      10
9        7
Name: count, dtype: int64
********************
Location
Sector 150, Noida          1303
Sector 73, Noida            355
Sector 107, Noida           226
Sector 128, Noida           193
Sector 78, Noida            179
                           ...
Chhajarsi Colony, Noida       1
Bahlolpur, Noida              1
Sector 101, Noida             1
Sector 16, Noida              1
Sector 91, Noida              1
Name: count, Length: 91, dtype: int64
********************
Price
1.05 Cr    64
25 L       49
1.5 Cr     45
1.25 Cr    43
45 L       43
           ..
82.5 L      1
29.74 L     1
30.52 L     1
29.82 L     1
28.96 L     1
Name: count, Length: 923, dtype: int64
********************

In [8]:
df.isna().sum()

Unnamed: 0      0
Area in Sqrt    0
No.of Bhk       0
Location        0
Price           0
dtype: int64

In [9]:
df.drop(columns = ['Unnamed: 0'],inplace =True)

In [11]:
df.head()

   Area in Sqrt  No.of Bhk                        Location     Price
0          3720          4               Sector 107, Noida    3.9 Cr
1          1625          3                Sector 50, Noida   1.15 Cr
2          1325          3               Sector 120, Noida      60 L
3           650          1                Sector 73, Noida      19 L
4           950          2  Phase 2 Noida Extension, Noida   25.99 L

In [13]:
df.describe()

       Area in Sqrt    No.of Bhk
count   4460.000000  4460.000000
mean    1983.312332     2.907175
std     1372.932820     1.087717
min      434.000000     1.000000
25%     1050.000000     2.000000
50%     1550.000000     3.000000
75%     2500.000000     3.000000
max    15000.000000    10.000000

In [ ]:
 # -- price per  sqrft nikalna h - df[price_per_sqrft] = df['price']*100000/df['area in sqrt']

In [21]:
df.head()

   Area in Sqrt  No.of Bhk                 Location     Price
0          3720          4               Sector 107    3.9 Cr
1          1625          3                Sector 50   1.15 Cr
2          1325          3               Sector 120      60 L
3           650          1                Sector 73      19 L
4           950          2  Phase 2 Noida Extension   25.99 L

In [20]:
df['Location']=df['Location'].str.split(",").str.get(0)

In [27]:
location_count= df['Location'].value_counts()

In [29]:
location_count_less = location_count[location_count<=10]
location_count_less

Location
Sector 37                                          10
Sector 18                                          10
Phase 2 Noida Extension                             9
Sector 14                                           9
Sector-106 Noida                                    8
Sector 22D Yamuna Expressway                        8
Sector 40                                           7
Sector 46                                           7
Urbainia Trinity Noida Extension Yakubpur Noida     7
Sector 61                                           7
Sector 39                                           6
Sector 151                                          6
Sector 19                                           6
Sector 118                                          6
Sector 34                                           6
Sector 149                                          6
Sector 51                                           5
rho 2                                               5
Sector 113                                          5
Sector 168                                          5
Sector 16B                                          5
Sector 27                                           5
Sector 28                                           5
Sector 30                                           4
Sector 71                                           4
Sector 102                                          4
Sector 36                                           4
Sector 117                                          4
Sector 52                                           3
Sector 47                                           3
Sector 93B                                          2
Sector 122                                          2
Sector 26                                           2
Sector 15                                           2
Sector 92                                           2
Yeida                                               2
Sector 25 Yamuna Express Way                        2
Sector 81                                           2
Sector1                                             1
Sector 14A                                          1
Sector 12                                           1
Sector 56                                           1
Dallupura                                           1
Sector 33                                           1
Sector 22                                           1
Sector 70                                           1
Sector 129                                          1
Chhajarsi Colony                                    1
Bahlolpur                                           1
Sector 101                                          1
Sector 16                                           1
Sector 91                                           1
Name: count, dtype: int64

In [30]:
df['Location'] = df['Location'].apply(lambda x : 'other' if x in location_count_less else x)

In [33]:
df['Location'].value_counts()

Location
Sector 150                      1303
Sector 73                        355
Sector 107                       226
other                            209
Sector 128                       193
Sector 78                        179
Sector 49                        170
Sector 79                        139
Sector 75                        126
Sector 108                       120
Sector 77                        119
Sector 110                       116
Sector 43                        114
Sector 137                       111
Sector 121                        86
Sector 45                         86
Sector 44                         81
Sector 152                        79
Sector 94                         74
Sector 93A                        61
Sector 50                         49
Sector 74                         42
Sector 143B                       41
Sector 104                        38
Sector 143                        36
Sector 76                         33
Sector 17A Yamuna Expressway      32
Sector 100                        30
Sector 144                        28
Sector 41                         25
Sector 93                         21
Sector 15A                        20
Sector 82                         20
Sector 72                         18
Sector 120                        15
Sector 62                         15
Sector 19 Yamuna Expressway       13
Sector 134                        13
Sector 105                        12
Sector 119                        12
Name: count, dtype: int64

In [34]:
df.shape

(4460, 4)

In [35]:
df[df['Location'] == 'other']

      Area in Sqrt  No.of Bhk Location     Price
4              950          2    other   25.99 L
18             950          2    other    24.5 L
33             690          1    other   20.99 L
37            6480          6    other   9.25 Cr
40             953          2    other   39.59 L
...            ...        ...      ...       ...
4325           950          2    other   28.75 L
4327           954          2    other   28.25 L
4384          1500          3    other      42 L
4391           800          2    other   29.87 L
4412          1995          4    other   1.04 Cr

[209 rows x 4 columns]

In [37]:
df.to_csv('cleaned.csv',index=False)